### ISSUE TITLE
information du projet dans le README

### ISSUE THREAD

**Issue by bernard-ng** [devscast/devscast.org#11]
besoin d'avoir le point important du projet dans le README
- [x] rajout des informations de status (test, build, ci, ...)
- [x] description
- [x] but et object
- [ ] cible
- [ ] fonctionnalité

**Comment by juniorngangeli** [comment]
Le lien de la page vers la page wiki se trouvant dans le fichier `Readme.md` revoie vers la même page.
Est-ce qu'il est encore pertinent de le garder ?

**Comment by bernard-ng** [comment]
> Le lien de la page vers la page wiki se trouvant dans le fichier `Readme.md` revoie vers la même page.
> 
> Est-ce qu'il est encore pertinent de le garder ?

La page wiki arrive bientôt
