### ISSUE TITLE
Newsletter 

### ISSUE THREAD

**Issue by jocelinkisenga** [devscast/devscast.org#19]
Bonjour la communauté. 
Vu l'évolution de la plate-forme **devscast**, il y aurait-il pas moyen qu'on ajoute le système de **news letter **? Il y a de ce moment que nous ne sommes pas connecté sur nos réseaux sociaux, et que nous consultons nos boîtes mails. Pour cela nous serons alerté en temps utile et profiter de notre blog ou notre podcast.

**Comment by bernard-ng** [comment]
cela sera fait, une fois l'application en production !
