### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by bernard-ng** [devscast/devscast.org#8]
module podcast 

- [x] crud podcast
- [x] steaming podcast
- [x] generation du feed.rss
- [x] podcast en serie
- [x] podcast featured 
- [x] nombre d'ecoute (stream)
- [x] data analysis
- [x] reactions (comment and likes)

vu que nous hébergeons notre propre podcast, il est donc possible d'avoir des stats et des chiffres sur l'ecoute et les plateformes

**Comment by MarienMupenda** [comment]
Si possible ajouter la possibilité de réagir sur un podcast, (like, comment, star ..), Bravo 👏🏾 la team.

**Comment by bernard-ng** [comment]
> Si possible ajouter la possibilité de réagir sur un podcast, (like, comment, star ..), Bravo 👏🏾 la team.

@MarienMupenda On prend en compte cela

**Comment by juniorngangeli** [comment]
Il serait aussi intéressant de donner la possibilité de voir des sujets similaire lorsqu'on se retrouve sur la page d'un podcast.
Like this one here : 
[Comprendre le web3](https://devscast.tech/podcasts/comprendre-web3-11)
